// Plik konfiguracyjny słów
// Format każdego wpisu: { pl, romaji, hiragana }
//   pl      – słowo po polsku
//   romaji  – wymowa w zapisie łacińskim
//   hiragana – poprawna odpowiedź (znaki hiragany)

const WORDS = [
  { pl: "woda",        romaji: "mizu",    hiragana: "みず"     },
  { pl: "ogień",       romaji: "hi",      hiragana: "ひ"       },
  { pl: "góra",        romaji: "yama",    hiragana: "やま"     },
  { pl: "rzeka",       romaji: "kawa",    hiragana: "かわ"     },
  { pl: "morze",       romaji: "umi",     hiragana: "うみ"     },
  { pl: "niebo",       romaji: "sora",    hiragana: "そら"     },
  { pl: "kwiat",       romaji: "hana",    hiragana: "はな"     },
  { pl: "drzewo",      romaji: "ki",      hiragana: "き"       },
  { pl: "kamień",      romaji: "ishi",    hiragana: "いし"     },
  { pl: "księżyc",     romaji: "tsuki",   hiragana: "つき"     },
  { pl: "słońce",      romaji: "taiyou",  hiragana: "たいよう" },
  { pl: "ryba",        romaji: "sakana",  hiragana: "さかな"   },
  { pl: "ptak",        romaji: "tori",    hiragana: "とり"     },
  { pl: "kot",         romaji: "neko",    hiragana: "ねこ"     },
  { pl: "pies",        romaji: "inu",     hiragana: "いぬ"     },
  { pl: "dom",         romaji: "ie",      hiragana: "いえ"     },
  { pl: "droga",       romaji: "michi",   hiragana: "みち"     },
  { pl: "noc",         romaji: "yoru",    hiragana: "よる"     },
  { pl: "ranek",       romaji: "asa",     hiragana: "あさ"     },
  { pl: "herbata",     romaji: "ocha",    hiragana: "おちゃ"   },
  { pl: "serce",       romaji: "kokoro",  hiragana: "こころ"   },
  { pl: "wiatr",       romaji: "kaze",    hiragana: "かぜ"     },
  { pl: "wiosna",      romaji: "haru",    hiragana: "はる"     },
  { pl: "lato",        romaji: "natsu",   hiragana: "なつ"     },
  { pl: "jesień",      romaji: "aki",     hiragana: "あき"     },
  { pl: "zima",        romaji: "fuyu",    hiragana: "ふゆ"     },
  { pl: "miłość",      romaji: "ai",      hiragana: "あい"     },
  { pl: "gwiazda",     romaji: "hoshi",   hiragana: "ほし"     },
  { pl: "chmura",      romaji: "kumo",    hiragana: "くも"     },
  { pl: "deszcz",      romaji: "ame",     hiragana: "あめ"     },
  { pl: "śnieg",       romaji: "yuki",    hiragana: "ゆき"     },
  { pl: "oko",         romaji: "me",      hiragana: "め"       },
  { pl: "ręka",        romaji: "te",      hiragana: "て"       },
  { pl: "człowiek",    romaji: "hito",    hiragana: "ひと"     },
  { pl: "dziecko",     romaji: "ko",      hiragana: "こ"       },
  { pl: "mężczyzna",   romaji: "otoko",   hiragana: "おとこ"   },
  { pl: "kobieta",     romaji: "onna",    hiragana: "おんな"   },
  { pl: "ojciec",      romaji: "chichi",  hiragana: "ちち"     },
  { pl: "matka",       romaji: "haha",    hiragana: "はは"     },
  { pl: "miasto",      romaji: "machi",   hiragana: "まち"     },
  { pl: "ryż",         romaji: "kome",    hiragana: "こめ"     },
  { pl: "jedzenie",    romaji: "tabemono",hiragana: "たべもの" },
  { pl: "szkoła",      romaji: "gakkou",  hiragana: "がっこう" },
  { pl: "pociąg",      romaji: "densha",  hiragana: "でんしゃ" },
  { pl: "biały",       romaji: "shiro",   hiragana: "しろ"     },
  { pl: "czarny",      romaji: "kuro",    hiragana: "くろ"     },
  { pl: "czerwony",    romaji: "aka",     hiragana: "あか"     },
  { pl: "niebieski",   romaji: "ao",      hiragana: "あお"     },
  { pl: "zielony",     romaji: "midori",  hiragana: "みどり"   },
  { pl: "duży",        romaji: "ookii",   hiragana: "おおきい" },
  { pl: "mały",        romaji: "chiisai", hiragana: "ちいさい" },
  { pl: "nowy",        romaji: "atarashii",hiragana:"あたらしい"},
  { pl: "stary",       romaji: "furui",   hiragana: "ふるい"   },
  { pl: "piękny",      romaji: "kirei",   hiragana: "きれい"   },
  { pl: "dziękuję",    romaji: "arigatou",hiragana: "ありがとう"},
  { pl: "przepraszam", romaji: "sumimasen",hiragana:"すみません"},
  { pl: "tak",         romaji: "hai",     hiragana: "はい"     },
  { pl: "nie",         romaji: "iie",     hiragana: "いいえ"   },
];
